---

- name: install packages in loop
  hosts: localhost
  become: yes
  tasks:
    
    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - telnet
        - vim
        - git

...